### PR TITLE
Add support for array-based bulk insert

### PR DESCRIPTION
**Pull request by FreddieWitherden**
This is the counterpart to https://github.com/libspatialindex/libspatialindex/pull/267

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
Test failures are expected as it depends on new functionality for libspatialindex.  For my case of inserting ~1 million points time goes from ~6s to ~1s.

**Comment by hobu** [comment]
These tests should be resilient to different versions of libspatialindex. Rtree releases are not pinned to specific libspatialindex releases.

**Comment by FreddieWitherden** [comment]
> These tests should be resilient to different versions of libspatialindex. Rtree releases are not pinned to specific libspatialindex releases.

Have updated the PR so we catch the exceptions.  Does this approach seem reasonable (assuming it checks out test wise?)

**Comment by FreddieWitherden** [comment]
Just a short note about the implementation: the inputs for this are required to be NumPy arrays however I've been careful to not import NumPy so it is not a dependency of the library.  This should be reasonably flexible and anyone looking to seriously take advantage of the bulk capabilities really needs to be using NumPy (or a compatible alternative) anyway.

**Pull request merged**
