### PR TITLE
Use Read the Docs

### LINKED ISSUE #84: Documentation is outdated
http://toblerity.github.com/rtree/ (in the info here) redirects to http://toblerity.org/rtree/ which is the documentation for 0.7.0, when there have been 4 releases after that.

### PR DESCRIPTION
**Pull request by Juanlu001**
Fix #84

### CODE REVIEW

**Comment by Juanlu001** [comment]
The result can be seen here:

http://juanlu001-rtree.readthedocs.io/en/latest/

**Comment by Juanlu001** [comment]
For some reason, pytest is not installed in the Python 3.3 environment. What do you want me to do about it?

**Comment by sgillies** [comment]
@Juanlu001 could you please add a `- pip install pytest` just before `- pip install -e .` in the .travis.yml file? I think that should do it.

**Comment by Juanlu001** [comment]
The problem was with using `pytest` in Python 3.3, instead (I guess) `py.test`. I fixed it by using `python -m pytest`.

**Pull request merged**
