### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by mwtoews**

### CODE REVIEW

**Comment by EwoutH** [comment]
Just to inform you, it looks like the [release workflow](https://github.com/Toblerity/rtree/actions/runs/7582586537/job/20653048616) failed and didn't upload to PyPI.

**Comment by hobu** [comment]
The publishing token stuff had expired. PyPI has a new way of doing trusted publishers now. I have enabled it for this repository.

https://docs.pypi.org/trusted-publishers/

**Comment by mwtoews** [comment]
I can twine upload the artefacts, but @hobu needs to add me as a pypi.org maintainer for Rtree

**Comment by mwtoews** [comment]
Thanks for your patience, https://pypi.org/project/Rtree/1.2.0/ is now ready!

**Pull request merged**
