### PR TITLE
CI/RLS: upgrade to libspatialindex-2.0.0

### PR DESCRIPTION
**Pull request by mwtoews**
Towards #315.

This PR does the following:

- Upgrade libspatialindex from 1.9.3 to 2.0.0
- Remove the unneeded ci/CMakeLists.txt
- Use cmake install, removing the unneeded lib subdirs
- Remove the soversion number and symlinks for the library name (via [`CMAKE_PLATFORM_NO_VERSIONED_SONAME=ON`](https://cmake.org/cmake/help/latest/variable/CMAKE_PLATFORM_NO_VERSIONED_SONAME.html))
- It turns out the cibuildwheel tests on different python versions (via tox) was misleading, as it was not testing the built-wheel but the local source tree and sidx library build. This is fixed with `pytest --import-mode=importlib` 
- Consequently, the musllinux wheels on PyPI are "broken", as verified with `docker run -it --rm alpine:3.18 /bin/sh --login` then `apk add py3-pip`, `pip install rtree`, `python -c "import rtree"` to observe error. This is resolved by setting rpath for libspatialindex described next.
- Use `CMAKE_INSTALL_RPATH` only for macOS. On Linux, `$ORIGIN` seems to confuse auditwheel and prevents creation of `Rtree.libs`. It want's LD_LIBRARY_PATH set while repairing the wheel. But the `$ORIGIN`  rpath is still needed for musllinux, so manually add this last step in repair_wheel.py
- Simplify copying directory trees in setup.py with [copy_tree](https://github.com/pypa/distutils/blob/4e6d97db1b4364cb184960f477c3e78435332646/distutils/cmd.py#L364)

### CODE REVIEW

**Comment by hobu** [comment]
Waiting on you to merge this @mwtoews. Should we fire a release afterward?

**Comment by mwtoews** [comment]
there one thing that I'm sorting out before merge, as I want to keep the linux lib dir in Rtree.libs, since I see downstream packages rely on this.

**Comment by mwtoews** [comment]
There is yet another big list of changes on the build-side, updated in the PR description. This is ready to review by anyone, I'll probably merge it in another day after I've had a chance to carefully review the artefacts.

**Comment by EwoutH** [comment]
This looks like an amazing clean-up!

One thing I noticed, is that in the build CI [vcpython27](https://community.chocolatey.org/packages/vcpython27) is installed on Windows:

https://github.com/Toblerity/rtree/blob/d42650ccd78a413ce016a8528a859ed8ab20c1ee/.github/workflows/deploy.yml#L43-L47

Is this still needed, or can it be updated?

**Comment by mwtoews** [comment]
It looks like vcpython27 was added in 2020 with #174, at the time when MSBuild was used. Perhaps the existing ilammy/msvc-dev-cmd is sufficient, since cl.exe is needed for `cmake -G Ninja` (in ci/install_libspatialindex.bat).

**Pull request merged**
