### PR TITLE
Apply pyupgrade --py37-plus --keep-runtime-typing, with mods

### PR DESCRIPTION
**Pull request by mwtoews**
Modernize the code base to Python 3.7+ using [pyupgrade](https://github.com/asottile/pyupgrade) with a few manual modifications for string formatting. Also change a message with "LASError" (from libLAS) to simply "Error".

The initial command was:
```
pyupgrade --py37-plus --keep-runtime-typing `find . -name "*.py"`
```

### CODE REVIEW

**Review by adamjstewart — APPROVED** [review]
Never heard of this tool before, this is great! This would have really helped with one of my recent projects.

**Comment by adamjstewart** [comment]
There's also some `PY3` code in `tests/test_index.py` that's worth removing. I can do it in a separate PR unless you want to do it in this PR.

**Comment by hobu** [comment]
doesn't matter to me

**Comment by hobu** [comment]
merged it. Make a new PR for the test tweak if you want.

**Pull request merged**
