### PR TITLE
Rtree Wheel Infrastructure

### PR DESCRIPTION
**Pull request by mikedh**
Hey, thanks for the great project! I made a pass at building wheels that bundle `libspatialindex` as it seems like something that [trips people up](https://github.com/mikedh/trimesh/issues/941). Happy to close this if it isn't desirable, and thought I'd open it for feedback before I put more time into it.   

### Changes
- Breaks out library finding logic into separate `rtree/finder` submodule so that `setup.py` can reuse it.
- Refactors or replaces wheel building logic with [cibuildwheel](https://github.com/joerick/cibuildwheel). I think it's a great project, and I've been able to get it to build [every flavor of wheel](https://github.com/drufat/triangle/pull/51) for other projects.

### Status
- without tests enabled this is [building wheels successfully](https://github.com/mikedh/rtree/actions/runs/195635148) on every flavor of Python on Linux.
- I think I'm running into actual [issues](https://github.com/mikedh/rtree/runs/947672648?check_suite_focus=true#step:7:5010) on some variants of Python that I don't fully understand. The nice thing about cibuildwheel is it runs the tests using the version of the package from the actual wheel and these may be actual issues. 

### Todo
- Fix tests on Linux platforms.
- Better finder logic for "module path" (it's currently a cheap hack that only works on Linux for testing).
- Get wheels building on MacOS and Windows.

### CODE REVIEW

**Comment by mikedh** [comment]
> This is awesome. 🎊

Great! I'll try to get this over the finish line then haha. It might be a few weeks, there is potentially a lot of surface area here 😁.

>    There are flake8 failures now that must be cleaned up.

Absolutely, I'll do a formatting and docstring pass before removing the [WIP] and draft-pr tags and make sure linters pass.

>    Is there a build/test loop of the wheels for each platform? That's what I was trying to do with my scripts and not having much success with. Its great that the wheels are built, but we have no way to know they haven't rotted without a test loop.

Yeah that is my favorite part: https://cibuildwheel.readthedocs.io/en/stable/options/#test-command
The only thing I'm not totally certain of is how to make sure that it's using the `libspatialindex` from the wheel, although I guess we could *not* do a `make install`. 


Any ideas about that `cp27m` failure? Looks like a dtype thing:
```
x = array([ 2, 92, 51, 55, 26, 95,  7, 81, 38, 22, 58, 89, 91, 83, 98, 37, 70,
   ...6, 64, 79, 94, 40, 32, 46, 47, 15, 68, 10,  0, 80, 56,
       50], dtype=int64)
y = array([ 2., 92., 51., 55., 26., 95.,  7., 81., 38., 22., 58., 89., 91.,
      ..., 79., 94., 40., 32., 46., 47., 15., 68., 10.,
        0., 80., 56., 50., 30.])
atol = 1e-08, rtol = 1e-05

    def within_tol(x, y, atol, rtol):
        with errstate(invalid='ignore'):
>           return less_equal(abs(x-y), atol + rtol * abs(y))
E           ValueError: operands could not be broadcast together with shapes (69,) (70,)

```

**Comment by hobu** [comment]
> Any ideas about that cp27m failure? Looks like a dtype thing:

No. We were planning to ditch 2.7 soon anyway.

**Comment by mikedh** [comment]
Apologies for the delay, I'll try to get this into fighting shape within the next 2 weeks :smile:

**Comment by hobu** [comment]
This looks dreadfully miserable. Thanks 🙏  for keeping at it!

**Comment by mikedh** [comment]
Haha thanks! I can't get any of the build stuff to reproduce locally on a Windows machine (like, at all) so it's kind of like throwing rocks at a tree and hoping one sticks 😛. I'm definitely blowing that 2 week estimate, at least it's back to conventionally f**ed compilation rather than esoteric CI stuff. 

```
FAILED: src/CMakeFiles/spatialindex.dir/capi/DataStream.cc.obj 
C:\msys64\mingw64\bin\clang.exe -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMCPY=1 -DHAVE_MEMSET=1 -DSIDX_DLL_EXPORT=1 -DSIDX_DLL_IMPORT=1 -Dspatialindex_EXPORTS -I../src/../include -O2 -g -DNDEBUG /wd4068 -std=gnu++11 -MD -MT src/CMakeFiles/spatialindex.dir/capi/DataStream.cc.obj -MF src\CMakeFiles\spatialindex.dir\capi\DataStream.cc.obj.d -o src/CMakeFiles/spatialindex.dir/capi/DataStream.cc.obj -c ../src/capi/DataStream.cc
clang: error: no such file or directory: '/wd4068'
ninja: build stopped: subcommand failed.
```

My lessons learned thus far:
- `cibuildwheel` on *Windows* uses the base environment (not Docker), so installing stuff in the Github actions directive carries through to the build. On Linux this is not true and you have to install everything through `CIBW_*` env scripts.
- Github Actions for Windows includes LLVM but it isn't in the default `PATH` for unknowable, probably dumb, reasons.
- Previous Windows CI examples for `libspatialindex` use Clang/Ninja so I think that is probably the best bet? It works on my local machine 🤷

**Comment by mrclary** [comment]
@mikedh, thanks for your work on this. The [Spyder project](https://github.com/spyder-ide/spyder) would really like to add this as a dependency for our macOS application (spyder-ide/spyder#14243).

FYI, if I install `rtree` from your the wheel artifact in this PR, it does not find `libspatialindex` from the wheel. If I `brew install spatialindex`, then it seems to work.
```bash
>> pip install ~/Downloads/wheels/Rtree-0.9.5-cp38-cp38-macosx_10_9_x86_64.whl
>> python -c 'import rtree'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rclary/.pyenv/versions/3.8.6/envs/spy-build/lib/python3.8/site-packages/rtree/__init__.py", line 9, in <module>
    from .index import Rtree, Index  # noqa
  File "/Users/rclary/.pyenv/versions/3.8.6/envs/spy-build/lib/python3.8/site-packages/rtree/index.py", line 6, in <module>
    from . import core
  File "/Users/rclary/.pyenv/versions/3.8.6/envs/spy-build/lib/python3.8/site-packages/rtree/core.py", line 77, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/Users/rclary/.pyenv/versions/3.8.6/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/Users/rclary/.pyenv/versions/3.8.6/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found
>> brew install spatialindex
>> python -c 'import rtree'
>>
```

**Comment by hobu** [comment]
> AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found

Presumably the import logic in core.py will need some updates for the wheel scenario.

**Comment by mikedh** [comment]
Yeah all of the wheels are finally *building* now, but only the Linux one is working properly. I think I need more logic in `finder.py` for the other platforms, which I'll keep working on.

**Comment by hobu** [comment]
For your OSX RPATH troubles, you might try using https://pypi.org/project/delocate/ to rewrite the wheel rather than getting it set from CMake.

**Comment by mikedh** [comment]
> For your OSX RPATH troubles, you might try using https://pypi.org/project/delocate/ to rewrite the wheel rather than getting it set from CMake.

Good idea! Actually I probably just need to re-enable the cibuildwheel repair defaults on Mac. Linux + Windows wheels seem to be working in testing, Mac is the last holdout.

**Comment by hobu** [comment]
Making progress?

**Comment by mikedh** [comment]
Yeah I think this is pretty much ready to go! I've did some manual verifications of these wheels here and there, and they seem to work fine. Although there are approximately a bajillion of them, I haven't manually verified all of them. 

1. Wheels on Linux/Mac/Windows are building properly and running tests using the wheel against the whole matrix. The shared library search location repair is now done in the CI build scripts, and then we delete build directories and skip `make install` the shared library to make sure tests are being run with the wheel copy of the shared library (system-wide libraries were causing false success at certain points.)
2. I changed finder logic to work with `libspatialindex-dev` installed system-wide but as a last resort on posix. 
3. Conda build looks like it was fixed by adding search locations, but I haven’t tested this manually.
4. To get this to upload wheels to pypi you’ll have to add `PYPI_USERNAME` and `PYPI_PASSWORD` through the repo’s secrets interface and remove that `if false`

Here's the final tally:
```
Rtree-0.9.5-cp27-cp27m-linux_i686.whl
Rtree-0.9.5-cp27-cp27m-linux_x86_64.whl
Rtree-0.9.5-cp27-cp27m-macosx_10_15_x86_64.whl
Rtree-0.9.5-cp27-cp27mu-linux_i686.whl
Rtree-0.9.5-cp27-cp27mu-linux_x86_64.whl
Rtree-0.9.5-cp27-cp27m-win_amd64.whl
Rtree-0.9.5-cp35-cp35m-linux_i686.whl
Rtree-0.9.5-cp35-cp35m-linux_x86_64.whl
Rtree-0.9.5-cp35-cp35m-macosx_10_15_x86_64.whl
Rtree-0.9.5-cp35-cp35m-win_amd64.whl
Rtree-0.9.5-cp36-cp36m-linux_i686.whl
Rtree-0.9.5-cp36-cp36m-linux_x86_64.whl
Rtree-0.9.5-cp36-cp36m-macosx_10_15_x86_64.whl
Rtree-0.9.5-cp36-cp36m-win_amd64.whl
Rtree-0.9.5-cp37-cp37m-linux_i686.whl
Rtree-0.9.5-cp37-cp37m-linux_x86_64.whl
Rtree-0.9.5-cp37-cp37m-macosx_10_15_x86_64.whl
Rtree-0.9.5-cp37-cp37m-win_amd64.whl
Rtree-0.9.5-cp38-cp38-linux_i686.whl
Rtree-0.9.5-cp38-cp38-linux_x86_64.whl
Rtree-0.9.5-cp38-cp38-macosx_10_15_x86_64.whl
Rtree-0.9.5-cp38-cp38-win_amd64.whl
Rtree-0.9.5-cp39-cp39-linux_i686.whl
Rtree-0.9.5-cp39-cp39-linux_x86_64.whl
Rtree-0.9.5-cp39-cp39-macosx_10_15_x86_64.whl
Rtree-0.9.5-cp39-cp39-win_amd64.whl

```

**Review by hobu — APPROVED** [review]

**Comment by mikedh** [comment]
OK, manually verified the wheels from here:
https://github.com/mikedh/rtree/actions/runs/422194320

I made sure there was a fresh install (also check location of `rtree.core.rt`) and ran a simple 2D index check on the following:
- MacOS Python 3.9
- Windows x86_64 Python 3.8
- Linux x86_64 Python 3.8

This is probably fine to release, although happy to take additional feedback. Also anyone who wants to test the wheels at that link feel free, and if you could post your platform/version that would be great.

**Comment by hobu** [comment]
> This is probably fine to release, although happy to take additional feedback. 

Awesome, I'll push it out today or tomorrow

**Comment by hobu** [comment]
Released. https://pypi.org/project/Rtree/

The GHAs need to be updated to capture the wheels as artifacts and the Publish GHA needs to be updated to push them to PyPI upon release.

**Comment by hobu** [comment]
An unfortunate failure on  Windows Python 3.6 when the Conda package builds. Unclear why it is any different than 3.7 or 3.8, however.  https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=253701&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=393

**Comment by henryiii** [comment]
> The GHAs need to be updated to capture the wheels as artifacts and the Publish GHA needs to be updated to push them to PyPI upon release.

This might be helpful?
https://scikit-hep.org/developer/gha_wheels

**Comment by mikedh** [comment]
Thanks for merging! This will probably generate a whole bunch of issues like #175 just given the volume of platforms haha. I'll try to help address the higher priority/segfault/not-functioning ones when I get a chance.

**Comment by hobu** [comment]
Do you happen to remember why you were copying in your own CMakeLists.txt file? What is missing in libspatialindex's?

**Pull request merged**
